const fakedata = [
    {   
        "dni":1,
        "name": "mike",
        "rank": 2,
        "category":"tv",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Fhbo.png?alt=media&token=68ca3783-ed5f-4501-8bb2-b99d7e58033e",
        "namePlataform":"hbo",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"tv"
    },
    {   
        "dni":2,
        "name": "carlos",
        "rank": 3,
        "category":"tv",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Fnetflix.png?alt=media&token=5c1337bf-29e1-429e-9974-daeba6ce6efb",
        "namePlataform":"neflix",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"tv"
    },    {   
        "dni":3,
        "name": "fabian",
        "rank": 1,
        "category":"music",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Fyoutube.png?alt=media&token=ec2d624e-9207-45db-8882-48e2d407db6c",
        "namePlataform":"youtube",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"music"
    },
    {   
        "dni":4,
        "name": "jose",
        "rank": 4,
        "category":"tv",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Fhbo.png?alt=media&token=68ca3783-ed5f-4501-8bb2-b99d7e58033e",
        "namePlataform":"hbo",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"tv"
    },    {   
        "dni":5,
        "name": "marcos",
        "rank": 2,
        "category":"tv",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Famazon.png?alt=media&token=69a4a063-b51c-4458-8b45-af823032e4af",
        "namePlataform":"amazon",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"tv"
    },
    {   
        "dni":6,
        "name": "pedro",
        "rank": 3,
        "category":"tv",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Fdisney.png?alt=media&token=ce9c1681-21e4-4607-83ed-aa9f46510c8f",
        "namePlataform":"disney",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"tv"
    },
    {   
        "dni":7,
        "name": "mike",
        "rank": 2,
        "category":"tv",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Fhbo.png?alt=media&token=68ca3783-ed5f-4501-8bb2-b99d7e58033e",
        "namePlataform":"hbo",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"tv"
    },
    {   
        "dni":8,
        "name": "carlos",
        "rank": 3,
        "category":"tv",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Fnetflix.png?alt=media&token=5c1337bf-29e1-429e-9974-daeba6ce6efb",
        "namePlataform":"neflix",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"tv"
    },    {   
        "dni":9,
        "name": "fabian",
        "rank": 1,
        "category":"music",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Fyoutube.png?alt=media&token=ec2d624e-9207-45db-8882-48e2d407db6c",
        "namePlataform":"youtube",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"music"
    },
    {   
        "dni":10,
        "name": "jose",
        "rank": 4,
        "category":"tv",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Fhbo.png?alt=media&token=68ca3783-ed5f-4501-8bb2-b99d7e58033e",
        "namePlataform":"hbo",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"tv"
    },    {   
        "dni":11,
        "name": "marcos",
        "rank": 2,
        "category":"tv",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Famazon.png?alt=media&token=69a4a063-b51c-4458-8b45-af823032e4af",
        "namePlataform":"amazon",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"tv"
    },
    {   
        "dni":,
        "name": "pedro",
        "rank": 3,
        "category":"tv",
        "verification":true,
        "plataform":"https://firebasestorage.googleapis.com/v0/b/addin-dev-mike.appspot.com/o/plataform%2Fdisney.png?alt=media&token=ce9c1681-21e4-4607-83ed-aa9f46510c8f",
        "namePlataform":"disney",
        "ahorro":5,
        "mensual":4.969,
        "anual":59.000,
        "avalible":1,
        "tag":"tv"
    }
]
module.exports={
    fakedata
}
